// packages/jointplus/apps/Layers/src/components/Chatbot/Chatbot.tsx
import React, { ReactElement, useCallback, useEffect, useRef, useState } from 'react';
import { Subscription } from 'rxjs';

import './Chatbot.scss';
import JointPlusService from '../../services/joint-plus.service';
import JsonEditor from './JsonEditor/JsonEditor';
import Inspector from './Inspector/Inspector';
import EventBusServiceContext from '../../services/event-bus-service.context';
import { EventBusService } from '../../services/event-bus.service';
import { SharedEvents } from '../../joint-plus/controller';
import { importGraphFromJSON, loadStencilShapes, zoomToFit } from '../../joint-plus/actions';
import { STENCIL_WIDTH } from '../../theme';
import { useLayersContext } from '../../services/layers.context';
import LayersPanel from '../LayersPanel/LayersPanel';

import exampleGraphJSON from '../../joint-plus/config/example-graph.json';

interface ChatbotProps {
    layers?: any[];
}

const ChatbotCore = ({ layers = [] }: ChatbotProps): ReactElement => {

    const elementRef = useRef(null);
    const toolbarRef = useRef(null);
    const stencilRef = useRef(null);
    const paperRef = useRef(null);

    const [joint, setJoint] = useState(null);
    const [eventBusService] = useState(new EventBusService());
    const [stencilOpened, setStencilOpened] = useState(true);
    const [jsonEditorOpened, setJsonEditorOpened] = useState(false);
    const [fileJSON, setFileJSON] = useState(null);
    const [subscriptions] = useState(new Subscription());

    const openFile = useCallback((json: Object): void => {
        setFileJSON(json);
        importGraphFromJSON(joint, json);
        zoomToFit(joint);
    }, [joint]);

    const onStart = useCallback((): void => {
        loadStencilShapes(joint);
        openFile(exampleGraphJSON);
    }, [joint, openFile]);

    const onJsonEditorChange = useCallback((json: Object): void => {
        if (joint) {
            importGraphFromJSON(joint, json);
        }
    }, [joint]);

    const onJointGraphChange = useCallback((json: Object): void => {
        setFileJSON(json);
    }, []);

    const onStencilToggle = useCallback((): void => {
        if (!joint) {
            return;
        }
        const { scroller, stencil } = joint;
        if (stencilOpened) {
            stencil.unfreeze();
            scroller.el.scrollLeft += STENCIL_WIDTH;
        } else {
            stencil.freeze();
            scroller.el.scrollLeft -= STENCIL_WIDTH;
        }
    }, [joint, stencilOpened]);

    const toggleJsonEditor = (): void => {
        setJsonEditorOpened(!jsonEditorOpened);
    };

    const toggleStencil = (): void => {
        setStencilOpened(!stencilOpened);
    };

    useEffect((): void => {
        onStencilToggle();
    }, [stencilOpened, onStencilToggle]);

    const setStencilContainerSize = useCallback((): void => {
        stencilRef.current.style.width = `${STENCIL_WIDTH}px`;
    }, []);

    useEffect(() => {
        subscriptions.add(
            eventBusService.subscribe(SharedEvents.GRAPH_CHANGED, (json: Object) => onJointGraphChange(json))
        );
        subscriptions.add(
            eventBusService.subscribe(SharedEvents.JSON_EDITOR_CHANGED, (json: Object) => onJsonEditorChange(json))
        );
    }, [eventBusService, subscriptions, onJointGraphChange, onJsonEditorChange]);

    useEffect(() => {
        setJoint(new JointPlusService(
            elementRef.current,
            paperRef.current,
            stencilRef.current,
            toolbarRef.current,
            eventBusService
        ));
    }, [eventBusService]);

    useEffect(() => {
        if (!joint) {
            return;
        }
        setStencilContainerSize();
        onStart();
    }, [joint, onStart, setStencilContainerSize]);

    useEffect(() => {
        if (!joint) {
            return;
        }
        return () => {
            subscriptions.unsubscribe();
            joint.destroy();
        };
    }, [joint, subscriptions]);

    // Handle layer visibility changes
    useEffect(() => {
        if (!joint) return;
        const portsLayer = layers.find(layer => layer.id === 'ports');
        if (portsLayer) {
            joint.setPortsVisibility(portsLayer.visible);
        }
        const connectionsLayer = layers.find(layer => layer.id === 'connections');
        if (connectionsLayer) {
            joint.setConnectionsVisibility(connectionsLayer.visible);
        }
        const nodeIconsLayer = layers.find(layer => layer.id === 'node-icons');
        if (nodeIconsLayer) {
            joint.setNodeIconsVisibility(nodeIconsLayer.visible);
        }
    }, [joint, layers]);

    return (
        <EventBusServiceContext.Provider value={eventBusService}>
            <div ref={elementRef} className="joint-scope chatbot">
                <div ref={toolbarRef}/>
                <div className="side-bar">
                    <div className="toggle-bar">
                        <div onClick={toggleStencil}
                             className={'icon toggle-stencil ' + (!stencilOpened ? 'disabled-icon' : '')}
                             data-tooltip="Toggle Element Palette"
                             data-tooltip-position-selector=".toggle-bar"/>
                        <div onClick={toggleJsonEditor}
                             className={'icon toggle-editor ' + (!jsonEditorOpened ? 'disabled-icon' : '')}
                             data-tooltip="Toggle JSON Editor"
                             data-tooltip-position-selector=".toggle-bar"/>
                    </div>
                    <div ref={stencilRef}
                         style={{ display: stencilOpened ? 'initial' : 'none' }}
                         className="stencil-container"/>
                </div>
                <div className="main-container">
                    <div ref={paperRef} className="paper-container"/>
                    <div style={{ display: jsonEditorOpened ? 'initial' : 'none' }}>
                        <JsonEditor content={fileJSON}/>
                    </div>
                </div>
                <Inspector/>
                <LayersPanel/>
            </div>
        </EventBusServiceContext.Provider>
    );
};

// Wrapper component that uses the layers context
const Chatbot = (): ReactElement => {
    const { layers } = useLayersContext();
    return <ChatbotCore layers={layers} />;
};

export default Chatbot;

// packages/jointplus/apps/Chatbot/VueTs/src/components/Chatbot/Chatbot.vue
<template>
    <div class="joint-scope chatbot">
        <div ref="toolbar"></div>
        <div class="side-bar">
            <div class="toggle-bar">
                <div @click="toggleStencil()" class="icon toggle-stencil"
                     :class="{'disabled-icon': !stencilOpened}"
                     data-tooltip="Toggle Element Palette"
                     data-tooltip-position-selector=".toggle-bar"></div>
                <div @click="toggleJsonEditor()" class="icon toggle-editor"
                     :class="{'disabled-icon': !jsonEditorOpened}"
                     data-tooltip="Toggle JSON Editor"
                     data-tooltip-position-selector=".toggle-bar"></div>
            </div>
            <div v-show="stencilOpened" ref="stencil" class="stencil-container"></div>
        </div>
        <div class="main-container">
            <div ref="paper" class="paper-container"></div>
            <JsonEditor :content="fileJSON" v-show="jsonEditorOpened"/>
        </div>
        <Inspector/>
    </div>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';
import { Subscription } from 'rxjs';

import JointPlusService from '../../services/joint-plus.service';
import JsonEditor from './Json-editor/Json-editor.vue';
import Inspector from './Inspector/Inspector.vue';
import { STENCIL_WIDTH } from '../../theme';
import { SharedEvents } from '../../joint-plus/controller';
import { importGraphFromJSON, loadStencilShapes, zoomToFit } from '../../joint-plus/actions';

import exampleGraphJSON from '../../joint-plus/config/example-graph.json';

@Component({
    components: {
        Inspector,
        JsonEditor
    }
})
export default class Chatbot extends Vue {

    public joint = null as JointPlusService;
    public stencilOpened = true;
    public jsonEditorOpened = true;
    public fileJSON = {};

    private subscriptions = new Subscription();

    public mounted(): void {
        const { $el, $refs: { paper, stencil, toolbar }, subscriptions, $eventBusService } = this;
        subscriptions.add(
            $eventBusService.subscribe(SharedEvents.GRAPH_CHANGED, (json: Object) => this.onJointGraphChange(json))
        );
        subscriptions.add(
            $eventBusService.subscribe(SharedEvents.JSON_EDITOR_CHANGED, (json: Object) => this.onJsonEditorChange(json))
        );

        this.joint = new JointPlusService(
            $el,
            paper as Element,
            stencil as Element,
            toolbar as Element,
            $eventBusService
        );
        this.setStencilContainerSize();
        this.onStart();
    }

    public beforeDestroy(): void {
        this.subscriptions.unsubscribe();
        this.joint.destroy();
    }

    public openFile(json: Object): void {
        const { joint } = this;
        this.fileJSON = json;
        importGraphFromJSON(joint, json);
        zoomToFit(joint);
    }

    public toggleJsonEditor(): void {
        this.jsonEditorOpened = !this.jsonEditorOpened;
    }

    public toggleStencil(): void {
        this.stencilOpened = !this.stencilOpened;
        this.onStencilToggle();
    }

    private onStart(): void {
        const { joint } = this;
        loadStencilShapes(joint);
        this.openFile(exampleGraphJSON);
    }

    private onJsonEditorChange(json: Object): void {
        const { joint } = this;
        if (joint) {
            importGraphFromJSON(joint, json);
        }
    }

    private onJointGraphChange(json: Object): void {
        this.fileJSON = json;
    }

    private setStencilContainerSize(): void {
        (this.$refs.stencil as HTMLDivElement).style.width = `${STENCIL_WIDTH}px`;
        this.onStencilToggle();
    }

    private onStencilToggle(): void {
        const { joint, stencilOpened } = this;
        const { scroller, stencil } = joint;
        if (stencilOpened) {
            stencil.unfreeze();
            scroller.el.scrollLeft += STENCIL_WIDTH;
        } else {
            stencil.freeze();
            scroller.el.scrollLeft -= STENCIL_WIDTH;
        }
    }
}
</script>

<style lang="scss">
@import "src/assets/fonts";

.chatbot {
    position: relative;
    width: 100%;
    height: 100%;
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    font-family: realist, sans-serif;
    display: flex;
    min-width: 900px;

    .main-container {
        display: flex;
        flex-flow: column;
        height: 100%;
        overflow: hidden;
        flex: 1;

        /*  Diagram  */
        .paper-container {
            position: relative;
            overflow: hidden;
            box-sizing: border-box;
            z-index: 1;
            flex: 1;
            background: #F8F9FA;
        }
    }

    /*  Sidebar  */
    .side-bar {
        height: 100%;
        max-width: 250px;
        z-index: 2;
        background: none;
        display: flex;

        .toggle-bar {
            height: 100%;
            width: 50px;
            background: #222222;
            z-index: 2;
            display: flex;
            flex-flow: column;
            align-items: center;
            padding: 13px;

            .icon {
                margin-bottom: 26px;
                font-size: 24px;
                color: #FFFFFF;
                cursor: pointer;

                &:before {
                    @include icon;
                }
            }

            .toggle-stencil {
                &:before {
                    content: '\E39D'
                }
            }

            .toggle-editor {
                &:before {
                    content: '\E86F'
                }
            }

            .disabled-icon {
                opacity: 0.35;
            }
        }

        .stencil-container {
            height: 100%;
            position: relative;
        }
    }
}
</style>
