// packages/pa-app-ui/src/components/Chatbot/Inspector/Inspector.tsx
import React, { ReactElement, useContext, useEffect, useState } from 'react';
import { dia, shapes } from '@joint/plus';
import { Subscription } from 'rxjs';

import MessageInspector from './MessageInspector';
import './Inspector.scss';
import LinkInspector from './LinkInspector';
import LabelInspector from './LabelInspector';
import eventBusServiceContext from '../../../services/event-bus-service.context';
import { SharedEvents } from '../../../joint-plus/controller';
import { ShapeTypesEnum } from '../../../joint-plus/shapes/app.shapes';

const Inspector = (): ReactElement => {
    const [cell, setCell] = useState<dia.Cell>(null);
    const [subscriptions] = useState(new Subscription());
    const [isOpen, setIsOpen] = useState(true);
    const eventBusService = useContext(eventBusServiceContext);

    const setSelection = (selection: dia.Cell[]): void => {
        const [selectedCell = null] = selection;
        setCell(selectedCell);
    };

    useEffect(() => {
        subscriptions.add(
            eventBusService.subscribe(SharedEvents.SELECTION_CHANGED, (selection: dia.Cell[]) => setSelection(selection))
        );
        return () => {
            subscriptions.unsubscribe();
        };
    }, [eventBusService, subscriptions]);

    const chooseInspector = (): ReactElement => {
        switch (cell.get('type')) {
            case ShapeTypesEnum.MESSAGE:
                return <MessageInspector cell={cell as shapes.app.Message}/>
            case ShapeTypesEnum.LINK:
                return <LinkInspector cell={cell as dia.Link}/>;
            case ShapeTypesEnum.FLOWCHART_START:
                return <LabelInspector cell={cell}/>;
            case ShapeTypesEnum.FLOWCHART_END:
                return <LabelInspector cell={cell}/>;
            default:
                return;
        }
    };

    const emptyInspector = (): ReactElement => {
        return (
            <>
                <h1>Component</h1>
                <label htmlFor="label">Label</label>
                <input disabled id="label"/>
            </>
        );
    };

    const togglePanel = (): void => {
        setIsOpen(prev => !prev);
    };

    return (
        <div className={'chatbot-inspector ' + (!cell ? 'disabled-chatbot-inspector' : '') + (isOpen ? '' : ' closed')}>
            <div className="inspector-header">
                <span>Inspector</span>
                <button 
                    className="inspector-toggle" 
                    onClick={togglePanel}
                    aria-label={isOpen ? 'Close inspector' : 'Open inspector'}
                >
                    {isOpen ? '−' : '+'}
                </button>
            </div>
            {isOpen && (
                <div className="inspector-content">
                    {
                        cell ? chooseInspector() : emptyInspector()
                    }
                </div>
            )}
        </div>
    );
};

export default Inspector;

// packages/jointplus/apps/Chatbot/Angular16/src/app/inspector/inspector.component.ts
/*! JointJS+ v4.1.1 - HTML5 Diagramming Framework - TRIAL VERSION

Copyright (c) 2025 client IO

 2025-11-10 


This Source Code Form is subject to the terms of the JointJS+ Trial License
, v. 2.0. If a copy of the JointJS+ License was not distributed with this
file, You can obtain one at https://www.jointjs.com/license
 or from the JointJS+ archive as was distributed by client IO. See the LICENSE file.*/


import {
    Component,
    OnDestroy,
    OnInit
} from '@angular/core';
import { Subscription } from 'rxjs';
import { dia } from '@joint/plus';

import { EventBusService } from '../../services/event-bus.service';
import { ShapeTypesEnum } from '../../joint-plus/shapes/app.shapes';
import { SharedEvents } from '../../joint-plus/controller';


@Component({
    selector: 'chatbot-inspector',
    templateUrl: './inspector.component.html',
    styleUrls: ['./inspector.component.scss']
})
export class InspectorComponent implements OnInit, OnDestroy {

    public cell: dia.Cell;
    public subscriptions = new Subscription();
    public shapeTypesEnum = ShapeTypesEnum;

    constructor(private readonly eventBusService: EventBusService) {
    }

    public ngOnInit(): void {
        this.subscriptions.add(
            this.eventBusService.subscribe(SharedEvents.SELECTION_CHANGED, (selection: dia.Cell[]) => this.setCell(selection))
        );
    }

    private setCell(selection: dia.Cell[]): void {
        const [cell = null] = selection;
        this.cell = cell;
    }

    public ngOnDestroy(): void {
        this.subscriptions.unsubscribe();
    }
}
